Update: Workflow

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -2,6 +2,8 @@ name: C/C++ CI Build
 
 on:
   push:
+    paths:
+      - 2024_03_06_With_Workflow/**
     branches: 
       - main
       - develop
@@ -32,19 +34,45 @@ jobs:
 
     - name: Create a Folder to store all the cpp Files compiled Results
       run: |
-        mkdir leetcode
+        mkdir leetcoder
         ls
 
-    - name: Build C++ Files
-    # find -name "*.${{ env.file_extention }}" => Find C++ Files
+    - name: Identify Newly Added Files
+      id: identify-files
       run: |
-        g++ -o out -I ./leetcode *.cpp leetcode/*.cpp
-      env:
-        file_extention: cpp
+        newly_added_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^2024_03_06_With_Workflow/' | grep '\.cpp$' || true)
+        echo "::set-output name=newly_added_files::$newly_added_files"
 
-    - name: Upload to Artifactory
-      uses: actions/upload-artifact@v4
-      with:
-        name: leetcode-artifact
-        path: leetcode
-        if-no-files-found: warn
+    - name: Compile C++ files
+      run: |
+        newly_added_files="${{ steps.identify-files.outputs.newly_added_files }}"
+        if [ -n "$newly_added_files" ]; then
+          echo "Compiling newly added C++ files:"
+          for file in $newly_added_files; do
+            g++ "$file" || { echo "Compilation failed for $file"; exit 1; }
+          done
+        else
+          echo "No newly added C++ files found."
+        fi
+  
+    - name: Raise issue on compilation failure
+      if: failure()
+      run: |
+        echo "Compilation failed for some C++ files. Please check and fix the issues." > compilation_failure.txt
+        gh issue create --title "Compilation Failure" --body "$(cat compilation_failure.txt)"
+
+
+    # - name: Build C++ Files
+    # # find -name "*.${{ env.file_extention }}" => Find C++ Files
+    # # g++ -g $(find -name "*.${{ env.file_extention }}") -o leetcoder/
+    #   run: |
+    #     make
+    #   env:
+    #     file_extention: cpp
+
+    # - name: Upload to Artifactory
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: leetcode-artifact
+    #     path: leetcoder
+    #     if-no-files-found: warn
